version: "3.8"
services:
  web:
    container_name: web
    image: web
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 8088:80